### ISSUE TITLE
ERROR, version 1.7.

### ISSUE THREAD

**Issue by iForbS-MC** [zRA1Nz/SkyWarsReloaded-Walruscode#3]
[19:59:10] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to SkyWarsReloaded v2.8.5
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.PlayerList.c(PlayerList.java:265) [Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.PlayerList.a(PlayerList.java:152) [Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.LoginListener.c(LoginListener.java:119) [Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.LoginListener.a(LoginListener.java:44) [Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
Caused by: java.lang.IllegalArgumentException: Entry cannot be longer than 16 characters!
    at org.bukkit.craftbukkit.v1_7_R4.scoreboard.CraftObjective.getScore(CraftObjective.java:98) ~[Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at com.walrusone.skywars.controllers.ScoreboardController.getScoreboard(ScoreboardController.java:62) ~[?:?]
    at com.walrusone.skywars.listeners.PlayerListener.givePlayerItems(PlayerListener.java:651) ~[?:?]
    at com.walrusone.skywars.listeners.PlayerListener.onPlayerJoin(PlayerListener.java:148) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    ... 14 more
[19:59:10] [Server thread/INFO]: morols[/81.177.58.148:50990] logged in with entity id 8 at ([world] -27.39981604277558, 70.0, 13.669692321906616)
[19:59:10] [Server thread/WARN]: [SkyWarsReloaded] Task #3257 for SkyWarsReloaded v2.8.5 generated an exception
java.lang.IllegalArgumentException: Entry cannot be longer than 16 characters!
    at org.bukkit.craftbukkit.v1_7_R4.scoreboard.CraftObjective.getScore(CraftObjective.java:98) ~[Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at com.walrusone.skywars.controllers.ScoreboardController.getScoreboard(ScoreboardController.java:62) ~[?:?]
    at com.walrusone.skywars.controllers.PlayerController$1.run(PlayerController.java:38) ~[?:?]
    at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641) [Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]

**Comment by spincs** [comment]
lknpojmp
mo
lm;mol
[pm[
pmp[
m

**Comment by bryanowen7** [comment]
You have to edit the Message.yml and make sure all scoreboard names are shorter than 16 characters.
